### ISSUE TITLE
Swift 3 issue

### ISSUE THREAD

**Issue by shoaibhassanWhizpool** [ovh/swift-ovh#7]
I am running this app into Xcode 8.3
and getting this error in class OVHAPIAccessRule.swift line 48.

    private static var __once1: () = { () -> Void in
            Once.rights = readOnlyRights("/*")
        }()
    
    private static var __once: () = { () -> Void in
            Once.rights = allRights("/*")
        }()

here Once is undeclared.please let me know how to fix this issue.

**Comment by cygy** [comment]
PR was merged this morning. Can you pull and try again ?

**Comment by shoaibhassanWhizpool** [comment]
That issue is fixed
Thank alot

**Comment by shoaibhassanWhizpool** [comment]
But facing another issue
 self.OVHAPI.get("/me", completion: {  (result, error, request, response) -> Void in
                print(result)
            })

always receiving response like this
{
    errorCode = "INVALID_CREDENTIAL";
    httpCode = "403 Forbidden";
    message = "This credential is not valid";
}

**Comment by cygy** [comment]
Please open a new issue.
